---
- name: Deploy Nginx container
  hosts: app
  become: true

  tasks:
    - name: Pull Nginx image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-app
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
